AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  PrefixLetters:
    Type: String
    Default: prod

Globals:
    Function:
        Runtime: nodejs18.x
        Timeout: 10
        Handler: app.lambdaHandler

Resources:
    #_____FUNCTIONS_____
    #Entry
    GetEntriesFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: src/entry/getEntries
            # Layers:
            #     - !Ref AppCommons
    GetEntryByIdFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: src/entry/getEntryById
            # Layers:
            #     - !Ref AppCommons

    #_____DATA SOURCES_____
    #Entry
    GetEntriesDataSource:
        Type: AWS::AppSync::DataSource
        Properties:
            ApiId: !GetAtt GraphQLApi.ApiId
            Name: GetEntriesDataSource
            Type: AWS_LAMBDA
            ServiceRoleArn: !GetAtt AppSyncServiceRole.Arn
            LambdaConfig:
                LambdaFunctionArn: !GetAtt GetEntriesFunction.Arn
    GetEntryByIdDataSource:
        Type: AWS::AppSync::DataSource
        Properties:
            ApiId: !GetAtt GraphQLApi.ApiId
            Name: GetEntryByIdDataSource
            Type: AWS_LAMBDA
            ServiceRoleArn: !GetAtt AppSyncServiceRole.Arn
            LambdaConfig:
                LambdaFunctionArn: !GetAtt GetEntryByIdFunction.Arn
    
    #_____RESOLVERS_____
    #Entry
    GetEntriesResolver:
        Type: AWS::AppSync::Resolver
        Properties:
            ApiId: !GetAtt GraphQLApi.ApiId
            FieldName: getEntries
            TypeName: Query
            DataSourceName: !GetAtt GetEntriesDataSource.Name
    GetEntryByIdResolver:
        Type: AWS::AppSync::Resolver
        Properties:
            ApiId: !GetAtt GraphQLApi.ApiId
            FieldName: getEntryById
            TypeName: Query
            DataSourceName: !GetAtt GetEntryByIdDataSource.Name

    #_____INIT GRAPHQL_____
    GraphQLApi:
        Type: AWS::AppSync::GraphQLApi
        Properties:
            Name: !Sub "${PrefixLetters}_CS3_GraphQL"
            AuthenticationType: OPENID_CONNECT
            OpenIDConnectConfig:
                ClientId: "AkNRE1qjj3nSef4AjwItuL4NrtMKx6Tn"
                Issuer: "https://dev-6m9zf0-9.us.auth0.com"
    GraphQLSchema:
        Type: AWS::AppSync::GraphQLSchema
        Properties:
            ApiId: !GetAtt GraphQLApi.ApiId
            DefinitionS3Location: "./schema.graphql"

    #_____LAYERS_____
    # AppCommons:
    #     Type: AWS::Serverless::LayerVersion
    #     Properties:
    #         ContentUri: libs
    #         CompatibleRuntimes:
    #             - python3.9

    #_____ROLES_____
    AppSyncServiceRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: 2012-10-17
                Statement:
                    - Effect: Allow
                      Principal:
                          Service: appsync.amazonaws.com
                      Action:
                          - sts:AssumeRole
            Policies:
                - PolicyName: AppSyncServiceRole
                  PolicyDocument:
                      Version: 2012-10-17
                      Statement:
                          - Effect: Allow
                            Action: lambda:invokeFunction
                            Resource:
                                - !Sub "arn:aws:lambda:${AWS::Region}:*:*"
